language: python

python:
 - "3.7"

before_install:
 - pip install coverage
 - pip install codecov 

install:
 - pip install -r requirements.txt

script:
 - coverge run test_comparemask.py 
 - coverge run test_applymask.py 

after_success:
 - codecov
