language: python

python:
 - "3.7"

before_install:
 - pip install coverage

install:
 - pip install -r requirements.txt

script:
 - coverage run -m unittest discover -s . -p test_applymask.py

after_success:
 - coveralls
